"""add cycle fields to workout sessions

Revision ID: 0e5ce78ce8f3
Revises: 7c5ff120a1b7
Create Date: 2026-04-03 16:03:08.721041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e5ce78ce8f3'
down_revision = '7c5ff120a1b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cycle_phase', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cycle_adapted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.drop_column('cycle_adapted')
        batch_op.drop_column('cycle_phase')

    # ### end Alembic commands ###
