"""fix cycle_adapted server default

Revision ID: 3ee87c1b43f1
Revises: 0e5ce78ce8f3
Create Date: 2026-04-03 16:07:41.219227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ee87c1b43f1'
down_revision = '0e5ce78ce8f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.alter_column(
            'cycle_adapted',
            existing_type=sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.alter_column(
            'cycle_adapted',
            existing_type=sa.Boolean(),
            nullable=True,
            server_default=None,
        )

    # ### end Alembic commands ###
