"""initial schema

Revision ID: 92312803e936
Revises: 
Create Date: 2026-03-30 15:46:16.981216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92312803e936'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('muscle_group', sa.String(length=100), nullable=True),
    sa.Column('equipment_needed', sa.String(length=100), nullable=True),
    sa.Column('contraindications', sa.JSON(), nullable=True),
    sa.Column('contraindication_severity', sa.String(length=20), nullable=True),
    sa.Column('mobility_requirements', sa.JSON(), nullable=True),
    sa.Column('posture_considerations', sa.JSON(), nullable=True),
    sa.Column('injury_modifications', sa.JSON(), nullable=True),
    sa.Column('muscle_position', sa.String(length=20), nullable=True),
    sa.Column('is_corrective', sa.Boolean(), nullable=True),
    sa.Column('is_prehab', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('body_fat_pct', sa.Float(), nullable=True),
    sa.Column('goal_primary', sa.String(length=50), nullable=True),
    sa.Column('goal_secondary', sa.JSON(), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('training_days_per_week', sa.Integer(), nullable=True),
    sa.Column('session_duration_min', sa.Integer(), nullable=True),
    sa.Column('equipment', sa.JSON(), nullable=True),
    sa.Column('injuries_current', sa.JSON(), nullable=True),
    sa.Column('injuries_history', sa.JSON(), nullable=True),
    sa.Column('postural_issues', sa.JSON(), nullable=True),
    sa.Column('mobility_issues', sa.JSON(), nullable=True),
    sa.Column('muscle_imbalances', sa.JSON(), nullable=True),
    sa.Column('menstrual_tracking', sa.Boolean(), nullable=True),
    sa.Column('cycle_length_days', sa.Integer(), nullable=True),
    sa.Column('last_period_date', sa.Date(), nullable=True),
    sa.Column('training_likes', sa.Text(), nullable=True),
    sa.Column('training_dislikes', sa.Text(), nullable=True),
    sa.Column('previous_methods', sa.JSON(), nullable=True),
    sa.Column('had_coach_before', sa.Boolean(), nullable=True),
    sa.Column('motivation_type', sa.String(length=20), nullable=True),
    sa.Column('onboarding_completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('ai_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('body_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('body_fat_pct', sa.Float(), nullable=True),
    sa.Column('waist_cm', sa.Float(), nullable=True),
    sa.Column('hips_cm', sa.Float(), nullable=True),
    sa.Column('chest_cm', sa.Float(), nullable=True),
    sa.Column('left_arm_cm', sa.Float(), nullable=True),
    sa.Column('right_arm_cm', sa.Float(), nullable=True),
    sa.Column('left_leg_cm', sa.Float(), nullable=True),
    sa.Column('right_leg_cm', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('energy_level', sa.Integer(), nullable=True),
    sa.Column('sleep_quality', sa.Integer(), nullable=True),
    sa.Column('stress_level', sa.Integer(), nullable=True),
    sa.Column('motivation', sa.Integer(), nullable=True),
    sa.Column('soreness_level', sa.Integer(), nullable=True),
    sa.Column('body_weight_kg', sa.Float(), nullable=True),
    sa.Column('cycle_day', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('injury_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('body_part', sa.String(length=100), nullable=False),
    sa.Column('side', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('aggravating_factors', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('saw_doctor', sa.Boolean(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pain_journal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('body_part', sa.String(length=100), nullable=False),
    sa.Column('pain_type', sa.String(length=20), nullable=True),
    sa.Column('intensity', sa.Integer(), nullable=True),
    sa.Column('when_occurs', sa.String(length=20), nullable=True),
    sa.Column('related_exercise_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('periodization_type', sa.String(length=20), nullable=False),
    sa.Column('total_weeks', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mesocycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('weeks_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('program_weeks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mesocycle_id', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['mesocycle_id'], ['mesocycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_week_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['program_week_id'], ['program_weeks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logged_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planned_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_exercise_id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('target_reps', sa.String(length=20), nullable=True),
    sa.Column('target_weight_kg', sa.Float(), nullable=True),
    sa.Column('target_rpe', sa.Float(), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['workout_exercise_id'], ['workout_exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logged_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logged_exercise_id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('actual_reps', sa.Integer(), nullable=True),
    sa.Column('actual_weight_kg', sa.Float(), nullable=True),
    sa.Column('actual_rpe', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['logged_exercise_id'], ['logged_exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logged_sets')
    op.drop_table('planned_sets')
    op.drop_table('logged_exercises')
    op.drop_table('workout_sessions')
    op.drop_table('workout_exercises')
    op.drop_table('workouts')
    op.drop_table('program_weeks')
    op.drop_table('mesocycles')
    op.drop_table('programs')
    op.drop_table('pain_journal')
    op.drop_table('injury_details')
    op.drop_table('daily_checkins')
    op.drop_table('body_measurements')
    op.drop_table('ai_conversations')
    op.drop_table('users')
    op.drop_table('exercises')
    # ### end Alembic commands ###
