name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: gym-coach.111miniapp.com
          username: root
          password: ${{ secrets.HETZNER_PASS }}
          script: |
            cd /root/body-coach-ai
            git pull origin main
            docker compose up -d --build
            docker compose exec -T app flask db upgrade
